build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with many properties, using incremental build is recommended
  # incremental: true

processors:
  active: true
  exclude: []
  # - 'DetektProgressListener'
  # - 'FunctionCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'ElementCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'

complexity:
  active: true
  CyclomaticComplexity:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    threshold: 6
  LargeClass:
    active: true
    threshold: 600

style:
  active: true
  MagicNumber:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**' ]
    ignoreNumbers: [ '-1', '0', '1', '2' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreNumbersInVariableNames: true
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID)'

Compose:
  active: true
  ComposeNamingUppercase:
    active: true
  ComposeParameterOrder:
    active: true
  ComposeModifierMissing:
    active: true
  ComposeLambdaOffset:
    active: true
  ComposeM2Api:
    active: true
  ComposePublicModifierMissing:
    active: true
